# Site identity
title: Australia Citizenship Test Policy
description: Help you pass the test faster

# Markdown engine (Kramdown is the GitHub Pages default)
markdown: kramdown

# Theme selection (Essential for styling Markdown)
theme: jekyll-theme-minimal

# Navigation settings
baseurl: "" # Set to "/repository-name" if your site is not at the root domain
url: "https://tuanlinhdang.github.io/app-docs"
